deployments:
  default:
    subdomain_port_mapping:
      - reaction:3000
      - django-cms:8000
      - airflow:8080
      - odoo:8069
    domain:
      - squashlabs.co
      - deployster.io
      - codescore.io
    port_forwarding: 80:80
    deployment_page_commands:
      Update:
        - DEBIAN_FRONTEND=noninteractive apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

