deployments:
  default:
    subdomain_port_mapping:
      - django-cms:8000
      - airflow:8080
      - odoo:8069
      - reaction:3000
    domain:
      - squashlabs.co
      - deployster.io
      - codescore.io