version: '3.4'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - django-airflow
      - odoo
      - reaction

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  mongo:
    image: mongo
    command: mongod --storageEngine=wiredTiger

  odoo:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  django-cms:
    image: divio/django-cms-preview
    ports:
      - 8000:80

  django-airflow:
    image: puckel/docker-airflow
    ports:
      - 8080:8080
    command: webserver

  reaction:
    image: reactioncommerce/reaction:latest
    depends_on:
      - mongo
    environment:
      ROOT_URL: "http://reaction--${SQUASH_DOMAIN}"
      MONGO_URL: "mongodb://mongo:27017/reaction"
    restart:
      always

volumes:
  odoo-web-data:
  odoo-db-data: